### ISSUE TITLE
Any way to disable/configure the "indicator"?

### ISSUE THREAD

**Issue by sole** [mozbrick/brick-tabbar#21]
I wanted to change the color and appearance of it and it confused me that it wasn't the bottom border of the selected tab, but a div that gets translated when the selected tab changes. Sure I can write a rule for `brick-tabbar .selected-indicator` but what I have ended up using is

``` css
brick-tabbar .selected-indicator {
  background-color: transparent;
}
```

in order to "disable" it.

I was thinking that perhaps Brick should be more neutral in that sense and make this either an optional feature or (harder to do) convert into a CSS rendering thing only rather than an element that is floating around.

Thoughts?
